name: agent_app_belle_house_immobilier
description: A comprehensive admin app for real estate agents to manage properties and listings.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9

  # Networking
  dio: ^5.4.0
  http: ^1.1.2
  connectivity_plus: ^5.0.2

  # Local Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  sqflite: ^2.3.0

  # Navigation
  go_router: ^12.1.3
  auto_route: ^7.9.2

  # UI Components
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  lottie: ^2.7.0

  # Forms & Validation
  formz: ^0.6.1
  reactive_forms: ^16.1.1

  # Image & Media
  image_picker: ^1.0.4
  image_cropper: ^5.0.1
  file_picker: ^6.1.1
  video_player: ^2.8.1
  photo_view: ^0.14.0
  flutter_image_compress: ^2.1.0

  # Location & Maps
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  google_maps_flutter: ^2.5.0
  location: ^5.0.3

  # Utilities
  intl: ^0.18.1
  uuid: ^4.2.1
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  logger: ^2.0.2+1
  path_provider: ^2.1.1
  url_launcher: ^6.2.2
  share_plus: ^7.2.1

  # Permissions
  permission_handler: ^11.2.0

  # Environment & Config
  flutter_dotenv: ^5.1.0
  flutter_config: ^2.0.2

  # Charts & Analytics
  fl_chart: ^0.65.0
  syncfusion_flutter_charts: ^24.1.41

  # Animations
  animations: ^2.0.8
  flutter_staggered_animations: ^1.1.1

  # Date & Time
  table_calendar: ^3.0.9
  omni_datetime_picker: ^1.0.9

  # PDF & Documents
  pdf: ^3.10.7
  printing: ^5.11.1

  # Testing Utilities (for integration with main app)
  mockito: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  auto_route_generator: ^7.3.2

  # Testing
  mocktail: ^1.0.2
  bloc_test: ^9.1.5
  integration_test:
    sdk: flutter

  # Linting & Analysis
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0

  # Icons & Assets
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.8

# Flutter configuration
flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/images/logos/
    - assets/images/icons/
    - assets/images/illustrations/
    - assets/images/placeholders/
    - assets/fonts/
    - assets/config/
    - .env.dev
    - .env.staging
    - .env.prod

  # Fonts
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700

    - family: CustomIcons
      fonts:
        - asset: assets/fonts/custom_icons.ttf

# Flutter launcher icons configuration
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logos/app_logo.png"
  min_sdk_android: 21

# Native splash screen configuration
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logos/splash_logo.png
  color_dark: "#1a1a1a"
  image_dark: assets/images/logos/splash_logo.png
  android_12:
    image: assets/images/logos/splash_logo.png
    color: "#ffffff"
